export const WORKFLOW_STAGES: string[] = [
  'ORDER_RECEIVED',
  'CONSULTATION',
  'MEASUREMENTS_CONFIRMED',
  'IN_PRODUCTION',
  'QUALITY_CHECK',
  'READY',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'CUSTOMER_CONFIRMED',
];

export type WorkflowStage =
  | 'ORDER_RECEIVED'
  | 'CONSULTATION'
  | 'MEASUREMENTS_CONFIRMED'
  | 'IN_PRODUCTION'
  | 'QUALITY_CHECK'
  | 'READY'
  | 'OUT_FOR_DELIVERY'
  | 'DELIVERED'
  | 'CUSTOMER_CONFIRMED';
